import { Blog1, Blog2, Blog3 } from "./assets"

export const products = [
  {
      "title": "DAMAS-2 D2 STYLE PLUS 2024 yil  salondan chiqdi. 8.500$ kelishilinadi.",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40612_image.jpg",
      "price": 107525000,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "8ba8aea0-6c45-4a3d-a779-9c587d8f0bb1",
      "created_at": "2024-09-06T20:26:36+05:00",
      "category": "Transport",
      "sub_category": "Yengil avtomashinalar",
      "is_favorite": true,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Isuzu bartavoy sotiladi",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40613_image.jpg",
      "price": 20000,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Навоий",
      "token": "b66e43d4-3ccf-4cbf-8603-452b72956e7c",
      "created_at": "2024-09-06T20:26:35+05:00",
      "category": "Transport",
      "sub_category": "Yuk mashinalari",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "UAZ bortvoy Gaz 21",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40614_image.jpg",
      "price": 2500,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "70ac4ec0-5e99-47ab-bf68-06dd994c5721",
      "created_at": "2024-09-06T20:26:35+05:00",
      "category": "Transport",
      "sub_category": "Yengil avtomashinalar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Press aparat class",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40615_image.jpg",
      "price": 45000000,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Жиззах",
      "token": "d2bdbb49-f752-4d5e-9bdc-b40a95a03e84",
      "created_at": "2024-09-06T20:26:34+05:00",
      "category": "Transport",
      "sub_category": "Qishloq xo'jalik texnikasi",
      "is_favorite": false,
      "original_price": 32000,
      "xit": true,
  },
  {
      "title": "Прадо 150 фараси сотилади",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40616_image.jpg",
      "price": 700,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Бухоро",
      "token": "256ac4f5-6084-4998-aa79-dd261e3703cd",
      "created_at": "2024-09-06T20:26:34+05:00",
      "category": "Transport",
      "sub_category": "Avto ehtiyot qismlari va aksessuarlar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": true,
  },
  {
      "title": "Lasetti jentra qilingan sotiladi",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40617_image.jpg",
      "price": 7000,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Самарқанд",
      "token": "095fb1c9-ddf9-4198-84ac-1966c7bae9ec",
      "created_at": "2024-09-06T20:26:34+05:00",
      "category": "Transport",
      "sub_category": "Yengil avtomashinalar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": true,
  },
  {
      "title": "Полуприцеп (ярим тиркама) сотилади.",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40618_image.jpg",
      "price": 23500,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Бухоро",
      "token": "395eeb14-a1d5-401d-95f8-2fc35260142a",
      "created_at": "2024-09-06T20:26:32+05:00",
      "category": "Transport",
      "sub_category": "Tirkamalar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "32,000$ Toyota 2009 Ideal sastayani",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40619_image.jpg",
      "price": 32000,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "d254c2f8-1867-4fc3-9c0d-e52f0a68674e",
      "created_at": "2024-09-06T20:25:57+05:00",
      "category": "Transport",
      "sub_category": "Yengil avtomashinalar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Ерёнгок арахис комбайн, Туркия, нархи 392 млн сум",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40620_image.jpg",
      "price": 34000,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "8e7a00f2-f439-4d2c-b692-e1cc7085245f",
      "created_at": "2024-09-06T20:25:55+05:00",
      "category": "Transport",
      "sub_category": "Qishloq xo'jalik texnikasi",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Pogruzchik sotiladi 1.8 kub",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40624_image.jpg",
      "price": 18200,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "d7052961-3444-4d38-a919-da970c83db3d",
      "created_at": "2024-09-06T20:25:49+05:00",
      "category": "Transport",
      "sub_category": "Maxsus texnika",
      "is_favorite": false,
      "original_price": 32000,
      "xit": true,
  },
  {
      "title": "Aryon 630 sotiladi",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40625_image.jpg",
      "price": 21000,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Наманган",
      "token": "d89bf0a5-0eb5-45a5-8934-af3f0c0e614d",
      "created_at": "2024-09-06T20:25:42+05:00",
      "category": "Transport",
      "sub_category": "Qishloq xo'jalik texnikasi",
      "is_favorite": false,
      "original_price": 32000,
      "xit": true,
  },
  {
      "title": "Jentra Gm original diska sotiladi srochna",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40626_image.jpg",
      "price": 340,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Қашқадарё",
      "token": "592a54f9-5949-45c3-8df6-afe7c261cd71",
      "created_at": "2024-09-06T20:25:37+05:00",
      "category": "Transport",
      "sub_category": "Shinalar, disklar va g'ildiraklar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": true,
  },
  {
      "title": "Зил 1979 урал матор холати яхши 7 газ балон 4 та орка балон",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40627_image.jpg",
      "price": 6000,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "7efdfb4e-d80d-411d-a708-e2cedf12115e",
      "created_at": "2024-09-06T20:25:36+05:00",
      "category": "Transport",
      "sub_category": "Yuk mashinalari",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "\"Active Foam Magic\" Grass",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40628_image.jpg",
      "price": 3600,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "133ec92e-8c9a-49ea-b57e-54cc7ed1a6bc",
      "created_at": "2024-09-06T20:25:36+05:00",
      "category": "Transport",
      "sub_category": "Avto ehtiyot qismlari va aksessuarlar",
      "is_favorite": true,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Задний Бампер + Задний Кузов от Hyundai Creta 2021 года, синего цвета.",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40629_image.jpg",
      "price": 800000,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "c1311e37-ae19-48fe-a4a6-c0d06a283cf1",
      "created_at": "2024-09-06T20:25:35+05:00",
      "category": "Transport",
      "sub_category": "Avto ehtiyot qismlari va aksessuarlar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Srochni sotiladi maskvich",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40630_image.jpg",
      "price": 1400,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "3bd00541-77b0-450b-a59b-c8b6df16cc1a",
      "created_at": "2024-09-06T20:25:35+05:00",
      "category": "Transport",
      "sub_category": "Yengil avtomashinalar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "235/55/17 yumsho balon Malibu Tracker Orlando",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40631_image.jpg",
      "price": 1300000,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "09b3e28e-9208-4bc2-9604-049233250811",
      "created_at": "2024-09-06T20:25:33+05:00",
      "category": "Transport",
      "sub_category": "Shinalar, disklar va g'ildiraklar",
      "is_favorite": true,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Трактор CASE PUMA 155 тайёр_ (пума 155)",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40632_image.jpg",
      "price": 1305595200,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "0552cd97-6ebf-45bd-978e-b525f7cd23e4",
      "created_at": "2024-09-06T20:25:32+05:00",
      "category": "Transport",
      "sub_category": "Qishloq xo'jalik texnikasi",
      "is_favorite": false,
      "original_price": 32000,
      "xit": true,
  },
  {
      "title": "Масляный фильтр LF9018",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40633_image.jpg",
      "price": 1500,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "0369347f-41aa-42d4-8115-71bbaf1c4265",
      "created_at": "2024-09-06T20:25:31+05:00",
      "category": "Transport",
      "sub_category": "Avto ehtiyot qismlari va aksessuarlar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": true,
  },
  {
      "title": "Масляный фильтр LF777 fleetguard",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40637_image.jpg",
      "price": 1500,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "61b479ef-5892-49b4-87f7-ff92fde45a47",
      "created_at": "2024-09-06T20:25:31+05:00",
      "category": "Transport",
      "sub_category": "Avto ehtiyot qismlari va aksessuarlar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Авто жентра мокрый асфальт",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40638_image.jpg",
      "price": 10500,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Фарғона",
      "token": "797570ce-11e8-4d4e-9565-a3520d206770",
      "created_at": "2024-09-06T20:25:31+05:00",
      "category": "Transport",
      "sub_category": "Yengil avtomashinalar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Лазер планировщиклар, EFE ва FARMER фирмалари, Туркия, 220 млн сум",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40639_image.jpg",
      "price": 220000000,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "a77533ec-403f-4aec-962a-602e18e5cd22",
      "created_at": "2024-09-06T20:25:29+05:00",
      "category": "Transport",
      "sub_category": "Qishloq xo'jalik texnikasi",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Продается Колёсный Экскаватор UMG Е170W",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40640_image.jpg",
      "price": 50000,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "f8cfa3b9-0ca3-425a-a67a-2a3442dc454e",
      "created_at": "2024-09-06T20:25:28+05:00",
      "category": "Transport",
      "sub_category": "Maxsus texnika",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Авточехлы для всех видов машины",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40641_image.jpg",
      "price": 350000,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "9f840d08-aa67-4b62-9141-34cd0e9350ce",
      "created_at": "2024-09-06T20:25:26+05:00",
      "category": "Transport",
      "sub_category": "Avto ehtiyot qismlari va aksessuarlar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": true,
  },
  {
      "title": "Orient Leasingda Tahoe Premier muddatli tulovda yillik godovoy 12%",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40642_image.jpg",
      "price": 1109274880,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Қашқадарё",
      "token": "b12e19fc-279f-48ec-8fd8-e18001d90a8c",
      "created_at": "2024-09-06T20:25:20+05:00",
      "category": "Transport",
      "sub_category": "Yengil avtomashinalar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": true,
  },
  {
      "title": "Gentra style 2023 yil Avtomat luyk abs diska mafon bor",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40643_image.jpg",
      "price": 15900,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "c49cc1e0-3723-478d-b5e9-627a553024b1",
      "created_at": "2024-09-06T20:25:15+05:00",
      "category": "Transport",
      "sub_category": "Yengil avtomashinalar",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Сеялка пиёз сабзи экишга, Туркия ва Италия, нархи 135 млн сум",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40644_image.jpg",
      "price": 135000000,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "ac0d361f-0c12-4e28-b474-1139252a5fb2",
      "created_at": "2024-09-06T20:25:01+05:00",
      "category": "Transport",
      "sub_category": "Qishloq xo'jalik texnikasi",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Велоскутер янги охирги маркаси.",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40645_image.jpg",
      "price": 5000000,
      "money_type": "Сўм",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "7d636be5-4f02-4f6e-938a-694746c3c6b7",
      "created_at": "2024-09-06T20:24:51+05:00",
      "category": "Transport",
      "sub_category": "Moto",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Tent urnatamz Labo changan gazel va boshqa turdagi barcha moshenalarga",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40646_image.jpg",
      "price": 0,
      "money_type": "UZS",
      "sotuv_shakli": "Айрибошлаш",
      "address": "Тошкент вилояти",
      "token": "2d9e1d2a-894d-4f6e-993f-7a87fece40e8",
      "created_at": "2024-09-06T20:24:47+05:00",
      "category": "Transport",
      "sub_category": "Yuk mashinalari",
      "is_favorite": false,
      "original_price": 32000,
      "xit": false,
  },
  {
      "title": "Комбайн мош ловия фасол учун, комбайн-подборщик, Туркия, 13000 доллар",
      "status": "tasdiqlandi",
      "image1": "https://api.borgo.uz/media/images/40650_image.jpg",
      "price": 13000,
      "money_type": "Евро",
      "sotuv_shakli": "Сотилади",
      "address": "Тошкент вилояти",
      "token": "893a5d00-c9a7-48a3-ac25-193734bef5c5",
      "created_at": "2024-09-06T20:24:44+05:00",
      "category": "Transport",
      "sub_category": "Qishloq xo'jalik texnikasi",
      "is_favorite": true,
      "original_price": 32000,
      "xit": true,
  }
]

export const blogs = [
    {
        id: 1,
        title: 'Во что обувать ребёнка осенью?',
        descriptions: 'Осень — это мокро, холодно и часто совсем не предсказуемо. И если родители предпочтут “нелётную” погоду переждать дома, то детей не удержать — им срочно нужно мерить лужи и “готовить кашку” в свежей грязи :) При какой...',
        comments_count: 12,
        views: 90,
        created_at: '18.09.2021',
        image: Blog1,
    },
    {
        id: 2,
        title: 'Как одевать ребенка осенью?',
        descriptions: 'Расскажем подробно, как одевать ребенка осенью по градусам, что важно предусмотреть на любой каприз погоды, а также поделимся нашим экспертным мнением, какая одежда лучше защитит от ветра и дождя, и как уже, наконец, разобраться в показат...',
        comments_count: 9,
        views: 234,
        created_at: '12.09.2021',
        image: Blog2,
    },
    {
        id: 3,
        title: 'Как выбрать размер обуви ребенку?',
        descriptions: 'Интернет-магазин — это очень удобно и экономит время. Однако для родителей возникает сложность с тем, как выбрать обувь ребёнку по размеру. Ведь не примеришь вживую, и страшно ошибиться. В этой статье расскажем, как правильно подобрать разме...',
        comments_count: 23,
        views: 190,
        created_at: '30.08.2021',
        image: Blog3,
    },
]